# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Fluxos de Caixa',
                'verbose_name': 'Fluxo de Caixa',
            },
        ),
        migrations.CreateModel(
            name='CashInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('_type', models.CharField(choices=[('M', 'Mensalidade'), ('D', 'Doações'), ('A', 'Entrada Avulsa')], max_length=1, verbose_name='Tipo de Entrada')),
                ('cash_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register_cashinput_flow', to='cash_register.CashFlow', verbose_name='Caixa')),
            ],
            options={
                'verbose_name_plural': 'Entradas de Dinheiro',
                'verbose_name': 'Entrada de Dinheiro',
            },
        ),
        migrations.CreateModel(
            name='CashOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('_type', models.CharField(choices=[('C', 'Compra de Materiais'), ('S', 'Pagamento Seguro')], max_length=1, verbose_name='Tipo de Entrada')),
                ('cash_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register_cashoutput_flow', to='cash_register.CashFlow', verbose_name='Caixa')),
            ],
            options={
                'verbose_name_plural': 'Saídas de Dinheiro',
                'verbose_name': 'Saída de Dinheiro',
            },
        ),
    ]
